/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as interfaces from "./interfaces";
export { ClawMachine__factory } from "./ClawMachine__factory";
export { GameToken__factory } from "./GameToken__factory";
export { MockChainlinkPriceFeed__factory } from "./MockChainlinkPriceFeed__factory";
export { PrizeNFT__factory } from "./PrizeNFT__factory";
