// Auto-generated by deploy-and-sync.ts - DO NOT EDIT MANUALLY
// Last updated: 2025-12-10T16:57:01.764Z
// Latest deployment: sepolia (chainId: 11155111)

export const CONTRACTS = {
  localhost: {
    gameToken: "0x5FbDB2315678afecb367f032d93F642f64180aa3",
    prizeNFT: "0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512",
    clawMachine: "0x9fE46736679d2D9a65F0992F2272dE9f3c7fa6e0",
  },
  sepolia: {
    gameToken: "0xb60ce62D3e638ec1d85f0FAaB5C0d4632152f812",
    prizeNFT: "0x817c36f86A616321D75BDE872C74f96B17886305",
    clawMachine: "0xE4642499800d4704eF03aF7bBda46BBf66f68AEd",
  }
};

export const ORACLE_ADDRESS = "0x1E8eeB986B71FEf99106f3De93A4B1F01Eff26e9";

// Deployment metadata for latest deployment
export const DEPLOYMENT_INFO = {
  network: "sepolia",
  chainId: 11155111,
  rpcUrl: "https://ethereum-sepolia-rpc.publicnode.com",
  explorerUrl: "https://sepolia.etherscan.io",
  deployedAt: "2025-12-10T16:57:01.764Z",
  deployer: "0x1E8eeB986B71FEf99106f3De93A4B1F01Eff26e9",
  blockNumbers: {
    gameToken: 0,
    prizeNFT: 0,
    clawMachine: 0,
  },
};
