// Auto-generated by deploy-and-sync.ts - DO NOT EDIT MANUALLY
// Last updated: 2025-11-27T21:19:53.989Z
// Latest deployment: hardhat (chainId: 1337)

export const CONTRACTS = {
  sepolia: {
    gameToken: "0xba2300B8c318b8054D7Bd688ADFd659bD4EBECc2",
    prizeNFT: "0x6e3703Fa98a6cEA8086599ef407cB863e7425759",
    clawMachine: "0x39f24541e076e8557D20b8CfE695DE72e2f9Ea25",
  },
  localhost: {
    gameToken: "0x5FbDB2315678afecb367f032d93F642f64180aa3",
    prizeNFT: "0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512",
    clawMachine: "0x9fE46736679d2D9a65F0992F2272dE9f3c7fa6e0",
  }
};

export const ORACLE_ADDRESS = "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266";

// Deployment metadata for latest deployment
export const DEPLOYMENT_INFO = {
  network: "hardhat",
  chainId: 1337,
  rpcUrl: "",
  explorerUrl: "",
  deployedAt: "2025-11-27T21:19:53.989Z",
  deployer: "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266",
  blockNumbers: {
    gameToken: 1,
    prizeNFT: 2,
    clawMachine: 3,
  },
};
