// Auto-generated by deploy-and-sync.ts - DO NOT EDIT MANUALLY
// Last updated: 2025-11-28T16:09:03.504Z
// Latest deployment: sepolia (chainId: 11155111)

export const CONTRACTS = {
  localhost: {
    gameToken: "0x5FbDB2315678afecb367f032d93F642f64180aa3",
    prizeNFT: "0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512",
    clawMachine: "0x9fE46736679d2D9a65F0992F2272dE9f3c7fa6e0",
  },
  sepolia: {
    gameToken: "0x2C7c4F884a06aA128347A3C28324C481058cdC18",
    prizeNFT: "0x7e0EC19E316728CCFA9bb1B0Be768E5c87AA8Ae4",
    clawMachine: "0x1dE0DCf5Dd47D9e9CE7425cd72f719dC6455B81f",
  }
};

export const ORACLE_ADDRESS = "0x1E8eeB986B71FEf99106f3De93A4B1F01Eff26e9";

// Deployment metadata for latest deployment
export const DEPLOYMENT_INFO = {
  network: "sepolia",
  chainId: 11155111,
  rpcUrl: "https://ethereum-sepolia-rpc.publicnode.com",
  explorerUrl: "https://sepolia.etherscan.io",
  deployedAt: "2025-11-28T16:09:03.504Z",
  deployer: "0x1E8eeB986B71FEf99106f3De93A4B1F01Eff26e9",
  blockNumbers: {
    gameToken: 0,
    prizeNFT: 0,
    clawMachine: 0,
  },
};
