/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface GameTokenInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "MAX_FAUCET_AMOUNT"
      | "MAX_FAUCET_COOLDOWN"
      | "MAX_SUPPLY"
      | "MIN_FAUCET_COOLDOWN"
      | "allowance"
      | "approve"
      | "balanceOf"
      | "buyTokens"
      | "canClaimFaucet"
      | "claimFaucet"
      | "decimals"
      | "faucetAmount"
      | "faucetCooldown"
      | "faucetCooldownRemaining"
      | "faucetEnabled"
      | "getTokenAmount"
      | "getTokenPriceEth"
      | "lastFaucetClaim"
      | "mint"
      | "name"
      | "owner"
      | "priceFeed"
      | "renounceOwnership"
      | "setFaucetAmount"
      | "setFaucetCooldown"
      | "setFaucetEnabled"
      | "setPriceFeed"
      | "setTokenPrice"
      | "setTokenPriceUsd"
      | "symbol"
      | "tokenPrice"
      | "tokenPriceUsd"
      | "totalSupply"
      | "transfer"
      | "transferFrom"
      | "transferOwnership"
      | "withdraw"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Approval"
      | "FaucetAmountUpdated"
      | "FaucetClaimed"
      | "FaucetCooldownUpdated"
      | "FaucetStatusUpdated"
      | "OwnershipTransferred"
      | "PriceFeedUpdated"
      | "TokenPriceUpdated"
      | "TokenPriceUsdUpdated"
      | "TokensPurchased"
      | "Transfer"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "MAX_FAUCET_AMOUNT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_FAUCET_COOLDOWN",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_SUPPLY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_FAUCET_COOLDOWN",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "allowance",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "approve",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "balanceOf",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "buyTokens", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "canClaimFaucet",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "claimFaucet",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "decimals", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "faucetAmount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "faucetCooldown",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "faucetCooldownRemaining",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "faucetEnabled",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTokenAmount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTokenPriceEth",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "lastFaucetClaim",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "mint",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "name", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "priceFeed", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setFaucetAmount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setFaucetCooldown",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setFaucetEnabled",
    values: [boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setPriceFeed",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setTokenPrice",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setTokenPriceUsd",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "symbol", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "tokenPrice",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "tokenPriceUsd",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalSupply",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transfer",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferFrom",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "withdraw", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "MAX_FAUCET_AMOUNT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_FAUCET_COOLDOWN",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "MAX_SUPPLY", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "MIN_FAUCET_COOLDOWN",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "allowance", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "approve", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "balanceOf", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "buyTokens", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "canClaimFaucet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimFaucet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "decimals", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "faucetAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "faucetCooldown",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "faucetCooldownRemaining",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "faucetEnabled",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTokenAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTokenPriceEth",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastFaucetClaim",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "mint", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "name", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "priceFeed", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setFaucetAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setFaucetCooldown",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setFaucetEnabled",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPriceFeed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTokenPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTokenPriceUsd",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "symbol", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "tokenPrice", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "tokenPriceUsd",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalSupply",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "transfer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferFrom",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
}

export namespace ApprovalEvent {
  export type InputTuple = [
    owner: AddressLike,
    spender: AddressLike,
    value: BigNumberish
  ];
  export type OutputTuple = [owner: string, spender: string, value: bigint];
  export interface OutputObject {
    owner: string;
    spender: string;
    value: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FaucetAmountUpdatedEvent {
  export type InputTuple = [oldAmount: BigNumberish, newAmount: BigNumberish];
  export type OutputTuple = [oldAmount: bigint, newAmount: bigint];
  export interface OutputObject {
    oldAmount: bigint;
    newAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FaucetClaimedEvent {
  export type InputTuple = [claimer: AddressLike, amount: BigNumberish];
  export type OutputTuple = [claimer: string, amount: bigint];
  export interface OutputObject {
    claimer: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FaucetCooldownUpdatedEvent {
  export type InputTuple = [
    oldCooldown: BigNumberish,
    newCooldown: BigNumberish
  ];
  export type OutputTuple = [oldCooldown: bigint, newCooldown: bigint];
  export interface OutputObject {
    oldCooldown: bigint;
    newCooldown: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FaucetStatusUpdatedEvent {
  export type InputTuple = [enabled: boolean];
  export type OutputTuple = [enabled: boolean];
  export interface OutputObject {
    enabled: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PriceFeedUpdatedEvent {
  export type InputTuple = [
    oldPriceFeed: AddressLike,
    newPriceFeed: AddressLike
  ];
  export type OutputTuple = [oldPriceFeed: string, newPriceFeed: string];
  export interface OutputObject {
    oldPriceFeed: string;
    newPriceFeed: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokenPriceUpdatedEvent {
  export type InputTuple = [oldPrice: BigNumberish, newPrice: BigNumberish];
  export type OutputTuple = [oldPrice: bigint, newPrice: bigint];
  export interface OutputObject {
    oldPrice: bigint;
    newPrice: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokenPriceUsdUpdatedEvent {
  export type InputTuple = [oldPrice: BigNumberish, newPrice: BigNumberish];
  export type OutputTuple = [oldPrice: bigint, newPrice: bigint];
  export interface OutputObject {
    oldPrice: bigint;
    newPrice: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokensPurchasedEvent {
  export type InputTuple = [
    buyer: AddressLike,
    amount: BigNumberish,
    cost: BigNumberish
  ];
  export type OutputTuple = [buyer: string, amount: bigint, cost: bigint];
  export interface OutputObject {
    buyer: string;
    amount: bigint;
    cost: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransferEvent {
  export type InputTuple = [
    from: AddressLike,
    to: AddressLike,
    value: BigNumberish
  ];
  export type OutputTuple = [from: string, to: string, value: bigint];
  export interface OutputObject {
    from: string;
    to: string;
    value: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface GameToken extends BaseContract {
  connect(runner?: ContractRunner | null): GameToken;
  waitForDeployment(): Promise<this>;

  interface: GameTokenInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  MAX_FAUCET_AMOUNT: TypedContractMethod<[], [bigint], "view">;

  MAX_FAUCET_COOLDOWN: TypedContractMethod<[], [bigint], "view">;

  MAX_SUPPLY: TypedContractMethod<[], [bigint], "view">;

  MIN_FAUCET_COOLDOWN: TypedContractMethod<[], [bigint], "view">;

  allowance: TypedContractMethod<
    [owner: AddressLike, spender: AddressLike],
    [bigint],
    "view"
  >;

  approve: TypedContractMethod<
    [spender: AddressLike, value: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  balanceOf: TypedContractMethod<[account: AddressLike], [bigint], "view">;

  buyTokens: TypedContractMethod<[], [void], "payable">;

  canClaimFaucet: TypedContractMethod<
    [account: AddressLike],
    [boolean],
    "view"
  >;

  claimFaucet: TypedContractMethod<[], [void], "nonpayable">;

  decimals: TypedContractMethod<[], [bigint], "view">;

  faucetAmount: TypedContractMethod<[], [bigint], "view">;

  faucetCooldown: TypedContractMethod<[], [bigint], "view">;

  faucetCooldownRemaining: TypedContractMethod<
    [account: AddressLike],
    [bigint],
    "view"
  >;

  faucetEnabled: TypedContractMethod<[], [boolean], "view">;

  getTokenAmount: TypedContractMethod<
    [ethAmount: BigNumberish],
    [bigint],
    "view"
  >;

  getTokenPriceEth: TypedContractMethod<[], [bigint], "view">;

  lastFaucetClaim: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  mint: TypedContractMethod<
    [to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  name: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  priceFeed: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setFaucetAmount: TypedContractMethod<
    [newAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  setFaucetCooldown: TypedContractMethod<
    [newCooldown: BigNumberish],
    [void],
    "nonpayable"
  >;

  setFaucetEnabled: TypedContractMethod<
    [enabled: boolean],
    [void],
    "nonpayable"
  >;

  setPriceFeed: TypedContractMethod<
    [newPriceFeed: AddressLike],
    [void],
    "nonpayable"
  >;

  setTokenPrice: TypedContractMethod<
    [newPrice: BigNumberish],
    [void],
    "nonpayable"
  >;

  setTokenPriceUsd: TypedContractMethod<
    [newPriceUsd: BigNumberish],
    [void],
    "nonpayable"
  >;

  symbol: TypedContractMethod<[], [string], "view">;

  tokenPrice: TypedContractMethod<[], [bigint], "view">;

  tokenPriceUsd: TypedContractMethod<[], [bigint], "view">;

  totalSupply: TypedContractMethod<[], [bigint], "view">;

  transfer: TypedContractMethod<
    [to: AddressLike, value: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  transferFrom: TypedContractMethod<
    [from: AddressLike, to: AddressLike, value: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  withdraw: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "MAX_FAUCET_AMOUNT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_FAUCET_COOLDOWN"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_SUPPLY"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_FAUCET_COOLDOWN"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "allowance"
  ): TypedContractMethod<
    [owner: AddressLike, spender: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "approve"
  ): TypedContractMethod<
    [spender: AddressLike, value: BigNumberish],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "balanceOf"
  ): TypedContractMethod<[account: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "buyTokens"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "canClaimFaucet"
  ): TypedContractMethod<[account: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "claimFaucet"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "decimals"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "faucetAmount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "faucetCooldown"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "faucetCooldownRemaining"
  ): TypedContractMethod<[account: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "faucetEnabled"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "getTokenAmount"
  ): TypedContractMethod<[ethAmount: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getTokenPriceEth"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "lastFaucetClaim"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "mint"
  ): TypedContractMethod<
    [to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "name"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "priceFeed"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setFaucetAmount"
  ): TypedContractMethod<[newAmount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setFaucetCooldown"
  ): TypedContractMethod<[newCooldown: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setFaucetEnabled"
  ): TypedContractMethod<[enabled: boolean], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPriceFeed"
  ): TypedContractMethod<[newPriceFeed: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setTokenPrice"
  ): TypedContractMethod<[newPrice: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setTokenPriceUsd"
  ): TypedContractMethod<[newPriceUsd: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "symbol"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "tokenPrice"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "tokenPriceUsd"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalSupply"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transfer"
  ): TypedContractMethod<
    [to: AddressLike, value: BigNumberish],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferFrom"
  ): TypedContractMethod<
    [from: AddressLike, to: AddressLike, value: BigNumberish],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "Approval"
  ): TypedContractEvent<
    ApprovalEvent.InputTuple,
    ApprovalEvent.OutputTuple,
    ApprovalEvent.OutputObject
  >;
  getEvent(
    key: "FaucetAmountUpdated"
  ): TypedContractEvent<
    FaucetAmountUpdatedEvent.InputTuple,
    FaucetAmountUpdatedEvent.OutputTuple,
    FaucetAmountUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "FaucetClaimed"
  ): TypedContractEvent<
    FaucetClaimedEvent.InputTuple,
    FaucetClaimedEvent.OutputTuple,
    FaucetClaimedEvent.OutputObject
  >;
  getEvent(
    key: "FaucetCooldownUpdated"
  ): TypedContractEvent<
    FaucetCooldownUpdatedEvent.InputTuple,
    FaucetCooldownUpdatedEvent.OutputTuple,
    FaucetCooldownUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "FaucetStatusUpdated"
  ): TypedContractEvent<
    FaucetStatusUpdatedEvent.InputTuple,
    FaucetStatusUpdatedEvent.OutputTuple,
    FaucetStatusUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PriceFeedUpdated"
  ): TypedContractEvent<
    PriceFeedUpdatedEvent.InputTuple,
    PriceFeedUpdatedEvent.OutputTuple,
    PriceFeedUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "TokenPriceUpdated"
  ): TypedContractEvent<
    TokenPriceUpdatedEvent.InputTuple,
    TokenPriceUpdatedEvent.OutputTuple,
    TokenPriceUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "TokenPriceUsdUpdated"
  ): TypedContractEvent<
    TokenPriceUsdUpdatedEvent.InputTuple,
    TokenPriceUsdUpdatedEvent.OutputTuple,
    TokenPriceUsdUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "TokensPurchased"
  ): TypedContractEvent<
    TokensPurchasedEvent.InputTuple,
    TokensPurchasedEvent.OutputTuple,
    TokensPurchasedEvent.OutputObject
  >;
  getEvent(
    key: "Transfer"
  ): TypedContractEvent<
    TransferEvent.InputTuple,
    TransferEvent.OutputTuple,
    TransferEvent.OutputObject
  >;

  filters: {
    "Approval(address,address,uint256)": TypedContractEvent<
      ApprovalEvent.InputTuple,
      ApprovalEvent.OutputTuple,
      ApprovalEvent.OutputObject
    >;
    Approval: TypedContractEvent<
      ApprovalEvent.InputTuple,
      ApprovalEvent.OutputTuple,
      ApprovalEvent.OutputObject
    >;

    "FaucetAmountUpdated(uint256,uint256)": TypedContractEvent<
      FaucetAmountUpdatedEvent.InputTuple,
      FaucetAmountUpdatedEvent.OutputTuple,
      FaucetAmountUpdatedEvent.OutputObject
    >;
    FaucetAmountUpdated: TypedContractEvent<
      FaucetAmountUpdatedEvent.InputTuple,
      FaucetAmountUpdatedEvent.OutputTuple,
      FaucetAmountUpdatedEvent.OutputObject
    >;

    "FaucetClaimed(address,uint256)": TypedContractEvent<
      FaucetClaimedEvent.InputTuple,
      FaucetClaimedEvent.OutputTuple,
      FaucetClaimedEvent.OutputObject
    >;
    FaucetClaimed: TypedContractEvent<
      FaucetClaimedEvent.InputTuple,
      FaucetClaimedEvent.OutputTuple,
      FaucetClaimedEvent.OutputObject
    >;

    "FaucetCooldownUpdated(uint256,uint256)": TypedContractEvent<
      FaucetCooldownUpdatedEvent.InputTuple,
      FaucetCooldownUpdatedEvent.OutputTuple,
      FaucetCooldownUpdatedEvent.OutputObject
    >;
    FaucetCooldownUpdated: TypedContractEvent<
      FaucetCooldownUpdatedEvent.InputTuple,
      FaucetCooldownUpdatedEvent.OutputTuple,
      FaucetCooldownUpdatedEvent.OutputObject
    >;

    "FaucetStatusUpdated(bool)": TypedContractEvent<
      FaucetStatusUpdatedEvent.InputTuple,
      FaucetStatusUpdatedEvent.OutputTuple,
      FaucetStatusUpdatedEvent.OutputObject
    >;
    FaucetStatusUpdated: TypedContractEvent<
      FaucetStatusUpdatedEvent.InputTuple,
      FaucetStatusUpdatedEvent.OutputTuple,
      FaucetStatusUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PriceFeedUpdated(address,address)": TypedContractEvent<
      PriceFeedUpdatedEvent.InputTuple,
      PriceFeedUpdatedEvent.OutputTuple,
      PriceFeedUpdatedEvent.OutputObject
    >;
    PriceFeedUpdated: TypedContractEvent<
      PriceFeedUpdatedEvent.InputTuple,
      PriceFeedUpdatedEvent.OutputTuple,
      PriceFeedUpdatedEvent.OutputObject
    >;

    "TokenPriceUpdated(uint256,uint256)": TypedContractEvent<
      TokenPriceUpdatedEvent.InputTuple,
      TokenPriceUpdatedEvent.OutputTuple,
      TokenPriceUpdatedEvent.OutputObject
    >;
    TokenPriceUpdated: TypedContractEvent<
      TokenPriceUpdatedEvent.InputTuple,
      TokenPriceUpdatedEvent.OutputTuple,
      TokenPriceUpdatedEvent.OutputObject
    >;

    "TokenPriceUsdUpdated(uint256,uint256)": TypedContractEvent<
      TokenPriceUsdUpdatedEvent.InputTuple,
      TokenPriceUsdUpdatedEvent.OutputTuple,
      TokenPriceUsdUpdatedEvent.OutputObject
    >;
    TokenPriceUsdUpdated: TypedContractEvent<
      TokenPriceUsdUpdatedEvent.InputTuple,
      TokenPriceUsdUpdatedEvent.OutputTuple,
      TokenPriceUsdUpdatedEvent.OutputObject
    >;

    "TokensPurchased(address,uint256,uint256)": TypedContractEvent<
      TokensPurchasedEvent.InputTuple,
      TokensPurchasedEvent.OutputTuple,
      TokensPurchasedEvent.OutputObject
    >;
    TokensPurchased: TypedContractEvent<
      TokensPurchasedEvent.InputTuple,
      TokensPurchasedEvent.OutputTuple,
      TokensPurchasedEvent.OutputObject
    >;

    "Transfer(address,address,uint256)": TypedContractEvent<
      TransferEvent.InputTuple,
      TransferEvent.OutputTuple,
      TransferEvent.OutputObject
    >;
    Transfer: TypedContractEvent<
      TransferEvent.InputTuple,
      TransferEvent.OutputTuple,
      TransferEvent.OutputObject
    >;
  };
}
