/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as interfaces from "./interfaces";
export type { interfaces };
export type { ClawMachine } from "./ClawMachine";
export type { GameToken } from "./GameToken";
export type { MockChainlinkPriceFeed } from "./MockChainlinkPriceFeed";
export type { PrizeNFT } from "./PrizeNFT";
