/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ClawMachine } from "./ClawMachine";
export type { GameToken } from "./GameToken";
export type { PrizeNFT } from "./PrizeNFT";
